# Generated by Django 5.2.7 on 2025-10-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(db_index=True, max_length=108)),
                ('start_time', models.DateTimeField()),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'occupancy_data',
                'ordering': ['location_id', 'start_time'],
                'indexes': [models.Index(fields=['location_id', 'start_time'], name='occupancy_d_locatio_1f9c81_idx')],
                'unique_together': {('location_id', 'start_time')},
            },
        ),
    ]
