# Generated by Django 5.2.7 on 2025-10-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='note',
            name='embedding_model',
        ),
    ]
