# Generated by Django 5.2.7 on 2025-10-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_embedding_remove_note_embedding_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbooking',
            name='raw',
        ),
    ]
