# Generated by Django 5.2.7 on 2025-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_labbooking_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctvframe',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='librarycheckout',
            name='raw',
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding_model',
            field=models.CharField(blank=True, default='InceptionResnetV1', max_length=128, null=True),
        ),
    ]
